name: instant_grrocery_delivery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  http: ^0.13.5
  hooks_riverpod: ^2.1.3
  # cached_network_image: ^3.2.3
  # path_provider: ^2.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fruit/
