name: instant_grrocery_delivery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  http: ^1.0.0
  hooks_riverpod: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0 # annotation for 'json_serializable'
  http_status_code: ^0.0.2
  number_paginator: ^0.2.3
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.5
  csc_picker: ^0.2.7
  material_dialogs: ^1.1.4
  flutter_gen: ^5.3.2
  flutter_hooks: ^0.20.1
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  device_preview: ^1.1.0
#  auto_route: ^7.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fruit/
#    - assets/fonts/roboto/
    - assets/fonts/dmsans/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/roboto/Roboto-Regular.ttf
#        - asset: assets/fonts/roboto/Roboto-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/roboto/Roboto-Thin.ttf
#          weight: 100



# flutter pub run build_runner build
#  flutter pub run build_runner watch --delete-conflicting-outputs