name: instant_grrocery_delivery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  dartz: ^0.10.1
  injectable: ^2.1.2
  shared_preferences: ^2.0.15
  http: ^1.0.0
  hooks_riverpod: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  http_status_code: ^0.0.2

  number_paginator: ^0.2.3
  pin_code_fields: ^7.4.0
  flutter_svg: ^2.0.5
  csc_picker: ^0.2.7
  # dio: ^5.1.1
  material_dialogs: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fruit/


# flutter pub run build_runner build